### ISSUE TITLE
Large timeout

### ISSUE THREAD

**Issue by zhourui123** [VelocityPowered/Velocity#215] opened 2019-06-08 13:30 UTC
The problem appears to be caused by an IllegalStateException.
I hope you can fix it urgently. This problem makes the server not work normally. Thank you very much.
https://gist.github.com/zhourui123/02e63f3d81e939d251c8f21ae59533e8
above link contain 2 log file, velocity log and mc server log
```
[21:19:54] [Velocity Event Executor - #1/ERROR]: Some errors occurred whilst posting event PluginMessageEvent{source=[server connection] ZX冰零 -> lobby-1, target=[connected player] ZX冰零 (/112.38.160.59:7189), identifier=BungeeCord (legacy), data=[0, 11, 80, 108, 97, 121, 101, 114, 67, 111, 117, 110, 116, 0, 5, 119, 97, 114, 45, 51], result=handled message at proxy}.
[21:19:54] [Velocity Event Executor - #24/ERROR]: #1: 

java.lang.IllegalStateException: Not connected to server!
	at com.velocitypowered.proxy.connection.backend.VelocityServerConnection.ensureConnected(VelocityServerConnection.java:171) ~[velocity-proxy-1.0.0-SNAPSHOT-all.jar:1.0.0-SNAPSHOT (git-94e5bec5-bunknown)]
	at com.velocitypowered.proxy.connection.backend.VelocityServerConnection.sendPluginMessage(VelocityServerConnection.java:213) ~[velocity-proxy-1.0.0-SNAPSHOT-all.jar:1.0.0-SNAPSHOT (git-94e5bec5-bunknown)]
	at com.velocitypowered.bungeequack.BungeeQuack.onPluginMessage(BungeeQuack.java:173) ~[?:?]
	at net.kyori.event.asm.generated.b5da3cc374.BungeeQuack-onPluginMessage-PluginMessageEvent-2.invoke(Unknown Source) ~[?:?]
	at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[velocity-proxy-1.0.0-SNAPSHOT-all.jar:1.0.0-SNAPSHOT (git-94e5bec5-bunknown)]
	at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[velocity-proxy-1.0.0-SNAPSHOT-all.jar:1.0.0-SNAPSHOT (git-94e5bec5-bunknown)]
	at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:136) ~[velocity-proxy-1.0.0-SNAPSHOT-all.jar:1.0.0-SNAPSHOT (git-94e5bec5-bunknown)]
	at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$0(VelocityEventManager.java:117) ~[velocity-proxy-1.0.0-SNAPSHOT-all.jar:1.0.0-SNAPSHOT (git-94e5bec5-bunknown)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

```

This gist show timeout cause by OutOfDirectMemoryError:
https://gist.github.com/zhourui123/e8c9d7d68766b44a5003d8d7741f2c3d

start flags:
java -Xms512M -Xmx10G -Dmfbl.env=product -Dio.netty.leakDetectionLevel=advanced -jar velocity-proxy-1.0.0-SNAPSHOT-all.jar

**Comment by hugmanrique** [comment] 2019-06-08 16:19
The first IllegalStateException was caused by the BungeeQuack plugin, mind moving the issue to https://github.com/VelocityPowered/BungeeQuack? The OutOfDirectMemoryError means you're running super low on RAM and Netty couldn't allocate a direct buffer in a off-heap region.

**Comment by astei** [comment] 2019-06-08 16:44
The `IllegalStateException` from BungeeQuack is a side effect from the `OutOfDirectMemoryError` which is trying to tell you that there is a memory leak.

Unfortunately, you run a custom version of Velocity, so I don't know if you've touched the Netty-handling code in Velocity or not. It is possible your changes to Velocity have created the issue.

**Comment by astei** [comment] 2019-06-08 22:00
I have looked through the logs of a fairly busy Velocity server (~100 player peak) and didn't find any leak issues there over the past two days.

I have also tried to trigger buffer leaks locally (by setting a 128MB heap size) with no success.

This clearly has something to do with changes you've made to Velocity yourself. I don't know what they are, but it's likely they introduced the issue. If you are willing to open-source your changes, I might be able to take a look but I'm pretty busy with other things.

I am closing this issue as this doesn't appear to be an upstream Velocity issue.

**Closed by astei** 2019-06-08 22:00 UTC

**Comment by zhourui123** [comment] 2019-06-09 01:44
Hi, Master Tux, the file contain 4 files, the diff and 3 file that i changed. I hope you can point out my mistake, thanks a lot!
https://gist.github.com/zhourui123/29dfe265c693a61b3a6cb2210f673ba4

**Comment by astei** [comment] 2019-06-09 08:33
This issue should be fixed in build 146

**Comment by theminecoder** [comment] 2019-06-09 08:37
I assume that patch was done for the Minecraft china client? It might be nice to potentially have this in the proxy (behind a config option of course) so that this patch doesn't have to be applied for every china server that wishes to use velocity

**Comment by zhourui123** [comment] 2019-06-09 09:03
Yes, maybe add for-china option to the configuration file.

**Comment by astei** [comment] 2019-06-09 09:17
I would consider it, but the option wouldn't be well-maintained by us because none of the core Velocity developers lives in mainland China (I am American, kashike is Canadian). If someone was willing to make sure that worked, then we'd probably go for it.
