### ISSUE TITLE
Error when connecting to a server.

### ISSUE THREAD

**Issue by PurpleIsEverything** [VelocityPowered/Velocity#78] opened 2018-09-12 02:20 UTC
This error occurred when connecting to an Engimatic 2: Expert Skyblock server AFTER connecting to a Sponge Vanilla lobby. Put here for tracking purposes.

https://paste.ubuntu.com/p/yqJf7ydb8d/

**Comment by astei** [comment] 2018-09-13 00:46
Does this issue recur if you use Waterfall?

**Comment by PurpleIsEverything** [comment] 2018-09-13 00:48
We've not encountered it when using Waterfall, it happens on the first attempt to connect to a server the next one usually succeeds.

**Comment by astei** [comment] 2018-09-13 00:48
I wonder if #80 helps, can you try it?

**Comment by PurpleIsEverything** [comment] 2018-09-13 00:49
Already have that merged, makes no difference.

**Comment by astei** [comment] 2018-09-13 00:50
I will get my local modded/vanilla network going tomorrow and will try to reproduce this.

**Comment by PurpleIsEverything** [comment] 2018-09-13 00:51
We've noticed this issue on multiple modded servers including Revelation, Direwolf20 1.12 and Enigmatica 2: Expert Skyblock it's not specific to a pack.

**Comment by astei** [comment] 2018-09-13 00:53
That's good to know. I wonder if there's a problem in Velocity or if there's a Forge issue we need to work around. I'm going to rope in @dualspiral just in case, but I think I'm going to need to make some time to seriously learn the internals of Forge.

This comment may well mark my entry into the world of modded Minecraft.

**Comment by dualspiral** [comment] 2018-09-13 08:07
Yeah, #80 should have nothing to do with this.

I don’t know what packet it is, but it might be that it’s a plugin message that is getting through before the FML handshake complete. I haven’t looked at the line that stacktrace references yet, but it might just be after the handshake completes and could be some race condition.

For context, the way Bungee handles the handshake is that we track the handshake packets, and I think we queue packets before sending them on at the end of each stage. I didn’t think it necessary here because of Velocity’s simplified handling. It might just be we need to queue packets.

I’d be interested in the Forge debug log for that server. It will tell us where in the handshake things go wrong (FML handily prints out each phase of the handshake), just having the error isn’t going to help much, I’m afraid...

**Comment by dualspiral** [comment] 2018-09-13 09:36
[velocity-proxy-1.0-SNAPSHOT-all.jar.zip](https://github.com/VelocityPowered/Velocity/files/2378643/velocity-proxy-1.0-SNAPSHOT-all.jar.zip)

Try this. It includes #80 and #83. I figure it's better to get you to test it as you've got the setup!

**Comment by PurpleIsEverything** [comment] 2018-09-13 17:46
Looking good so far, more testing should occur as the day goes on. Unfortunately we are still struggling with almost instant "Timeouts" from backend servers at random.

However that's out of the scope of this.

**Comment by astei** [comment] 2018-09-13 20:12
I've merged in #80 and #83. I will only be able to seriously look into the timeout stuff more deeply next week because I have exams and projects to do over the next 7 days or so.

**Comment by PurpleIsEverything** [comment] 2018-09-14 00:31
Unfortunately this didn't seem to be the solution the packet_handler errors have continued.

**Comment by PurpleIsEverything** [comment] 2018-09-14 16:18
I've also discovered the bad packet ID of 9 occurs on Vanilla lobby servers as well. Looking up that ID it is supposedly server bound plugin messaging.

**Comment by phase** [comment] 2018-09-14 17:19
If you're on 1.12.2, it's a [Serverbound Plugin Message](https://wiki.vg/index.php?title=Protocol&oldid=14204#Plugin_Message_.28serverbound.29). (It's `0x0A` on 1.13)

**Comment by astei** [comment] 2018-09-16 03:01
Is this fixed now?

**Comment by PurpleIsEverything** [comment] 2018-09-16 03:06
I haven't seen these messages after I changed everything over to writeIfJoined, though it could still be the wrong way to deal with this.

**Comment by astei** [comment] 2018-10-08 15:07
Since then, these have been replaced by timeout issues.

It looks like there isn't much Velocity can do about timeout problems, especially as these issues are also present in vanilla (see PaperMC/Paper#895). We'd love to fix all the keepalive issues, but a lot of mods tend to add connection delays which can cause this issue. The most we can do is allow you to set the read timeout, which we've done.

My recommendations:

* Poor connections and computers tend to exacerbate the problem. Try to send less data, such as by reducing server's `view-distance`.
* Reduce the number of heavy mods if you can, and file issues against those mods to try to make them more considerate of lower-end connections.

Velocity's keep-alive handling is very "passive" - we simply record keep alives and forward them onto the remote client/server. Velocity might be able to do something if this were a client problem, but these issues ultimately arise from the server, which we simply have no control over.

If anyone has a PR that can help alleviate the timeout issues on Forge, we are all ears. But for now, the only responsible thing to do for now is to close this issue.

**Closed by astei** 2018-10-08 15:07 UTC
Labels: bug, help wanted
