### ISSUE TITLE
Crashes Spongeforge Pixelmon Server

### ISSUE THREAD

**Issue by Karagra** [VelocityPowered/Velocity#184] opened 2019-04-03 07:55 UTC
If I leave the hub online for 10 minutes then try to join this crash happens everytime. Does not happen on Bungeecord being up days straight, Same plugins just swapped bungeecord with velocity

Velocity: Velocity 1.0-SNAPSHOT (git-564cb998-b85
Spongeforge: SpongeForge 1.12.2-2768-7.1.6-RC3616 
Forge: Forge 2809 

https://pastebin.com/HkU91Xsu

**Comment by dualspiral** [comment] 2019-04-03 08:30
I suspect this is the same as #183.

**Comment by astei** [comment] 2019-04-03 12:33
This is, in fact, a duplicate of #183.

**Closed by astei** 2019-04-03 12:33 UTC
