### ISSUE TITLE
Unable to interact with certain blocks in latest build

### ISSUE THREAD

**Issue by Willsr71** [VelocityPowered/Velocity#193] opened 2019-04-25 00:39 UTC
Right clicking certain blocks in the latest build does nothing. Most modded blocks are affected, and some vanilla ones include crafting tables and furnaces. Chests and doors still work just fine.

Known working build is [git-564cb998-b85](https://github.com/VelocityPowered/Velocity/commit/564cb998610b0b5051785524f488ee8344d163d4) according to /velocity version

**Comment by astei** [comment] 2019-04-25 00:54
I can't reproduce this under vanilla Minecraft, so this appears to be a Forge-specific issue. Going to investigate further.

**Comment by astei** [comment] 2019-04-25 01:09
I have tested myself (with the BuildCraft mod). This is definitely a Forge issue and needs further investigation.

**Comment by astei** [comment] 2019-04-25 01:23
If I transition servers, then the BuildCraft inventories (I used the Stirling Engine) starts working normally. So I think we can narrow things down to just the initial connection. This doesn't appear as bad as I thought but it still concerns me quite a bit and I need to look into this more.

**Comment by astei** [comment] 2019-04-25 01:29
I think this should be fixed now, please give the latest build a try.

**Closed** 2019-04-25 01:28 UTC
Labels: bug
