### ISSUE TITLE
[1.1.0] Brigadier commands are passed through to the backend

### ISSUE THREAD

**Issue by Proximyst** [VelocityPowered/Velocity#369] opened 2020-10-04 18:12 UTC
**Expected behaviour:**
An error message that the command does not exist, as it is registered with the proxy.

**Actual behaviour:**
The command that was not 100% matched was forwarded.

**Reproduction steps:**
1. Register a command such as: `/test <greedy string>` with an `#executes`.
1. Run `/test`; the backend will receive it.
1. Run `/test Hello, Velocity!`; the Velocity plugin will receive it.

**Comment by hugmanrique** [comment] 2020-10-04 19:16
Mind posting your code? What kind of command implementation are you using, `BrigadierCommand`? Does the user have permission to execute the command?

This is most likely a real issue (I recall having similar issues, maybe I forgot to test this case?), but prefer to remove the simple cases first.

**Comment by Proximyst** [comment] 2020-10-04 19:21
https://github.com/Proximyst/ban/blob/master/src/main/java/com/proximyst/ban/commands/UnbanCommand.java#L44-L53

The user has permission to execute the command:
![https://owo.whats-th.is/8pJXV4k.png](https://owo.whats-th.is/8pJXV4k.png)

**Comment by hugmanrique** [comment] 2020-10-04 19:28
Ah, I think you're missing an `#executes` on the argument-less "unban" literal builder. Do note the command will get forwarded if the user doesn't have permission (i.e. `requires` returns `false`). This is by design, an ugly alternative is to move the permission checking code to the `executes` function.

**Comment by Proximyst** [comment] 2020-10-04 19:32
I'd still like to see an option for it to capture all `unban` invocations (in this case, anyways) and treat them as if the backend does not exist, to avoid the ugly alternatives.

**Comment by hugmanrique** [comment] 2020-10-04 19:35
This follows Brigadier's conventions, you can also use a `SimpleCommand` with hinting.

**Comment by astei** [comment] 2021-07-07 04:59
Is this still an issue?

**Comment by hugmanrique** [comment] 2021-07-07 07:19
We still follow the same behavior, which is to mimic Brigadier. If a parent node has no `Command` and has children nodes, attempting to execute the parent fails (instead of randomly executing a child's `Command` as proposed). The alternative on https://github.com/VelocityPowered/Velocity/issues/369#issuecomment-703304786 works. Additionally, `Command`s can be reused on multiple nodes.

Attempting to implement this change would get messy real quick considering redirects.

**Comment by astei** [comment] 2021-07-08 07:09
Closing this issue as a WONTFIX due to a viable workaround and the complexity of working around this issue.

**Closed by astei** 2021-07-08 07:09 UTC
Labels: bug
