### ISSUE TITLE
Improve command API

### ISSUE THREAD

**Issue by Yeregorix** [VelocityPowered/Velocity#155] opened 2018-12-01 14:30 UTC
I've started writing a custom annotation based command framework for velocity and I've encountered some limitations so I'm writing this issue to list them and to propose solutions. My English is far from perfect, I hope to be understandable.

1. When executing a command, the arguments are already split into an array. For example, this can cause a problem when we want to write a /broadcast command, we don't have any information about the number of whitespaces between two words. It's also the source of unnecessary calculations when it's necessary to reconcatenate the arguments or to parse only the first arguments and not all arguments.
**Solution**: Replace `String[] args` with `String args` (in `Command#execute` and `Command#suggest`) and let the command executor split it only if it's necessary.

2. Currently we must decide in the `Command#hasPermission` method whether the handling of the command should be forwarded to the player's current server or not. Some commands need more flexibility, the choice is not always permission based and sometimes is only done at the end of the complete command execution.
**Solution**: Make `Command#execute` return a `boolean` which determines whether the handling of the command should be forwarded to the player's current server or not. `Command#hasPermission` should only be used to determines whether the player has the permission or not, as indicated by it's name.

3. When executing a command we sometimes want to check other things before checking if the command source has a specific permission. In my opinion, permission checking should be totally delegated to the command executor.
**Solution**: Remove `String[] args` in `Command#hasPermission` and only use this method in `VelocityCommandManager#offerSuggestions` to check if the command name should appear in the root aliases when generating suggestions.

4. There is currently no way to check if a command source is a console source. (Please don't tell me that we just need to use a `==` comparison with `ProxyServer#getConsoleCommandSource`. I'm speaking about something more general. Think about a plugin which would add multiple consoles.)
**Solution**: Add `ConsoleSource` interface.

5. The name of the method `Command#suggest` can make think that we will directly send the suggestions to the `CommandSource` during the method call.
**Solution**: Rename to `getSuggestions` or ``generateSuggestions`. It would be clearer.

6. Except for `Player`s,  `CommandSource`s currently don't have a name. It's sad 😢 .
**Solution**: Add a `getName` method returning a `String`. It can be really useful when logging command usages.

I know most of these are breaking changes but I think they are important for a clean API (Especially 1, 2 and 3), that's why I preferred to write this issue to discuss about it before making a PR.

Here is an example of what would the new `Command` interface look like: https://pastebin.com/Pm1kx5zF

**Comment by hugmanrique** [comment] 2018-12-01 17:10
While I like some of your suggestions, I feel like these would break lots of already built plugins and would require a major API version bump. I will now express my feelings towards all your suggestions:

1. Most commands treat arguments as "arguments". Your change would imply every command splitting the args for themselves, which would lead to less clean code and difficult integration with the new 1.13 suggestion system (that relies on spaces). A `CommandUtil.joinArgs(String[] args)` method could be provided:

```java
public static String joinArgs(String[] args) {
  return String.join(" ", args);
}
```

You said handling extra spaces between args is hard, but the [Javadocs](https://docs.oracle.com/javase/9/docs/api/java/lang/String.html#split-java.lang.String-) for `String#split` say the array will contain an empty string if there are two separator characters together (which the `String.join` method [joins correctly](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#join-java.lang.CharSequence-java.lang.CharSequence...-)).

2. I agree the forwarding handling in the `hasPermission` command is messy and can lead to confusion. Changing the return type of `#execute` will break lots of commands plus most MC developers are used to not having to return anything. An alternative might be a `Server#forwardCommand(Player, String command, String[] args)` or something better.

3. Relying on `#offerSuggestions` should not be a reliable way to decide whether a player has a certain permission to execute a subcommand. I prefer the current behavior, but that's my opinion.

4. I agree

5. This is unneeded API breakage, while `getSuggestions` might be a better name, the `suggest` method will only get called when the `CommandSource` asks for suggestions so the behavior is clear.

6. I agree, but what would a console command source return? `"Console"`? There might be a player with the same name :/

**Comment by astei** [comment] 2018-12-01 18:56
The Velocity command API was designed to be very simplistic to allow others to build on top of it without trying to get plugins to conform to our API. Accordingly, I mostly followed the example of Bukkit and BungeeCord, instead of trying something more exotic.

1. `String.join()` is a top-level function in Java 8, which will join the contents of an array with a separator. You can definitely use `String.join(" ", args)` without a problem.
2. This is too big of a breaking API change for me to accept. I'm sorry. (You can use `Player#spoofChatInput()` as a work around.)
3. Using `hasPermission()` for tab complete only would not be reliable. (It'd also be a breaking API change.)
4. There's already a way, but it's not too user intuitive. I could see myself adding this interface.
5. `suggest` is consistent with the `execute` method. I don't see any good reason to change this.
6. The console doesn't have a name because a name doesn't really make sense. I realize here that I've departed from the norm of having a `getName()` method on `CommandSource`. However, plugins make stupid assumptions about the contents of this call (oh, hey, it's a perfectly valid Minecraft username!) and I felt it was better to not expose such a function. (Even then, what would it return?)

**Comment by astei** [comment] 2018-12-01 19:38
1. At this point we've approached "personal" opinion territory. Most plugin developers expect an array here, and we provide one. If they prefer to work with a string, `String.join()` exists. (I also must mention that Velocity does not currently work with the 1.13 command framework. If we ever decide to do a 2.x.x, we'd probably make some changes to work better with 1.13.)
2. [BungeeCord](https://github.com/SpigotMC/BungeeCord/blob/master/api/src/main/java/net/md_5/bungee/api/plugin/Command.java#L53) does this.
3. My own personal view on `hasPermission()` is that it's an initial filter, just as in [Sponge](https://github.com/SpongePowered/SpongeAPI/blob/stable-7/src/main/java/org/spongepowered/api/command/CommandCallable.java#L74). With Velocity, if you're unsure, better to return `false` and have the backend server handle it.

Admittedly, I've been a bit trigger-happy with saying "breaking API change". Versioning will easily resolve this issue, however.

**Comment by kashike** [comment] 2018-12-01 21:56
1. I agree with @Yeregorix here - splitting only to have people join pretty much right after is useless - we can offer an additional interface that `default` implements `execute` for people who wish to use an array:
```java
  default void execute(final CommandSource source, final String args) {
    this.execute(source, args.split(" "));
  }

  void execute(final CommandSource source, final String[] args);
```
3. I agree with @astei - `hasPermission` is basically a "can the source execute this command at all?", and you can check for additional permissions within the appropriate methods.

**Comment by Yeregorix** [comment] 2018-12-08 10:53
1. @kashike The problem with the `default` method is that I still have to implement the method with an array even if I have implemented the other one. I'm more in favor of two separated interfaces.

3. @astei In Sponge `testPermission` is used as an initial filter during the command execution only if you're using the high level API (`CommandSpec`). In the low level one (`CommandCallable`), this method is only used to [list commands](https://github.com/SpongePowered/SpongeCommon/blob/9e07c8e78f9056d7cbce189b44c2a1a0d354d4d8/src/main/java/org/spongepowered/common/command/SpongeCommandFactory.java#L1024) available for display in the `/help` command and for auto-completion. Using the low level API, we have to do ourselves the permission check which give us way more choices.

**Comment by kashike** [comment] 2018-12-08 18:06
@Yeregorix 

>  we can offer an **additional interface** hat `default` implements `execute` for people who **wish to use an array**

**Comment by astei** [comment] 2018-12-08 21:34
I've created a new branch with the following changes that should work for most people:

* `hasPermission()` is now `shouldHandle()`, a more appropriate name.
* `execute()` now returns a `boolean`. (Likewise, appropriate changes were made to `CommandManager`.)

What I'm still dubious on:

* The need for a `String` based variant of `Command`. All currently proposed solutions are confusing and unintuitive for developers. Even if we were to introduce a separate `String`-based interface, that would be confusing because there's now two different ways to define a command in Velocity.
* The need to remove `args` from the now-renamed `shouldHandle()`.

**Comment by hugmanrique** [comment] 2018-12-08 21:47
I'm not 100% sold on the boolean return on `execute()`. I propose `shouldHandle` to be renamed to another thing and return an enum value from the following possible options:

`HANDLE, NO_PERMISSION, FORWARD`

**Comment by Yeregorix** [comment] 2018-12-10 16:38
@hugmanrique Imagine that to know whether I need to forward the command or not, I first need to do almost all the command execution logic. With the current API or your solution I must either execute twice times the command, which is not always a viable solution, either move the command execution in `shouldHandle` instead of `execute` which is even more illogic.

@astei The need to remove `args` is not very important, as an initial filter the plugin developer can ignore the arguments and only do a general check if he really need to more complex checks later. I understand that you want to keep it. 👍  However I think `hasPermission` sounded better than `shouldHandle` but I'm not a native English speaker so maybe that's because I don't see the nuance. ^^'
About the `String` variant I don't see what's wrong with the two APIs solution (low level/high level). That's the case in Sponge, nobody is lost and everyone can find what he need (simplicity or flexibility).

**Comment by astei** [comment] 2019-04-21 06:59
I am closing this issue for a few reasons:

* There hasn't been any discussion on this for more than 5 months.
* The command API is almost certain to be revisited in a future API release in light of the changes in 1.13. As stated before, I deliberately chose a very simple model for the API to promote plugin flexibility, and that would continue with any command API revamp.

I will consider everything in here when the command API is revamped.

**Closed by astei** 2019-04-21 06:59 UTC
Labels: enhancement

**Comment by astei** [comment] 2019-07-01 12:38
A string-based API will be making its way to Velocity 1.1.0.
