### ISSUE TITLE
Error when joining proxy without any server online

### ISSUE THREAD

**Issue by StealWonders** [VelocityPowered/Velocity#104] opened 2018-09-29 11:47 UTC
Hello fellow developers!
I tried connecting to the proxy without their being any server online or correctly configured.
Of course, it won't work, but there shouldn't be any error if coded well.
The follow error is displayed into the console:

> `[13:43:53 INFO]: [connected player] StealWonders (/127.0.0.1:6779) has connected[13:43:54 ERROR]: [connected player] StealWonders (/127.0.0.1:6779): unable to connect to server lobby
java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:30066
        at java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source) ~[?:1.8.0_102]
        at java.util.concurrent.CompletableFuture.completeRelay(Unknown Source) ~[?:1.8.0_102]
        at java.util.concurrent.CompletableFuture.uniRelay(Unknown Source) ~[?:1.8.0_102]
        at java.util.concurrent.CompletableFuture$UniRelay.tryFire(Unknown Source) ~[?:1.8.0_102]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:1.8.0_102]
        at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:1.8.0_102]
        at com.velocitypowered.proxy.connection.backend.VelocityServerConnection$1.operationComplete(VelocityServerConnection.java:87) ~[velocity.jar:1.0-SNAPSHOT (git-dc594e69, build 287)]
        at com.velocitypowered.proxy.connection.backend.VelocityServerConnection$1.operationComplete(VelocityServerConnection.java:77) ~[velocity.jar:1.0-SNAPSHOT (git-dc594e69, build 287)]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[velocity.jar:1.0-SNAPSHOT (git-dc594e69, build 287)]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504) ~[velocity.jar:1.0-SNAPSHOT (git-dc594e69, build 287)]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) ~[velocity.jar:1.0-SNAPSHOT (git-dc594e69, build 287)]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) ~[velocity.jar:1.0-SNAPSHOT (git-dc594e69, build 287)]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121) ~[velocity.jar:1.0-SNAPSHOT (git-dc594e69, build 287)]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327) ~[velocity.jar:1.0-SNAPSHOT (git-dc594e69, build 287)]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343) ~[velocity.jar:1.0-SNAPSHOT (git-dc594e69, build 287)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:616) ~[velocity.jar:1.0-SNAPSHOT (git-dc594e69, build 287)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563) ~[velocity.jar:1.0-SNAPSHOT (git-dc594e69, build 287)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480) ~[velocity.jar:1.0-SNAPSHOT (git-dc594e69, build 287)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) ~[velocity.jar:1.0-SNAPSHOT (git-dc594e69, build 287)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[velocity.jar:1.0-SNAPSHOT (git-dc594e69, build 287)]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:30066
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_102]
        at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source) ~[?:1.8.0_102]
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[velocity.jar:1.0-SNAPSHOT (git-dc594e69, build 287)]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[velocity.jar:1.0-SNAPSHOT (git-dc594e69, build 287)]
        ... 6 more
Caused by: java.net.ConnectException: Connection refused: no further information        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_102]
        at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source) ~[?:1.8.0_102]
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[velocity.jar:1.0-SNAPSHOT (git-dc594e69, build 287)]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[velocity.jar:1.0-SNAPSHOT (git-dc594e69, build 287)]
        ... 6 more
[13:43:54 INFO]: [connected player] StealWonders (/127.0.0.1:6779) has disconnected`

Maybe you are also able to make this message a bit clearer for normal users or might connect to the proxy: [Image](https://i.gyazo.com/6d11bef20460ba38e8424ba4410867b2.png)

**Comment by Leymooo** [comment] 2018-09-29 13:18
I think you need post this error to #58

**Comment by astei** [comment] 2018-09-29 18:18
This is a duplicate of #58.

**Closed by astei** 2018-09-29 18:18 UTC
