### ISSUE TITLE
Out of Date Client Join Error

### ISSUE THREAD

**Issue by ukdyl94** [VelocityPowered/Velocity#171] opened 2019-02-16 07:03 UTC
Get the following message when trying to join a 1.12.2 sponge vanilla lobby with a newer or older version of minecraft. You get spammed with the messages below but we're talking 10,000 messages every few seconds that causes velocity to crash.

`[06:36:13] [Netty epoll Worker #11/INFO]: [server connection] <username> -> lobby has connected
[06:36:13] [Netty epoll Worker #11/ERROR]: [connected player] <username> (/<ip address>): disconnected while connecting to lobby: multiplayer.disconnect.outdated_server
[06:36:13] [Netty epoll Worker #11/INFO]: [server connection] <username> -> lobby has disconnected
[06:36:13] [Netty epoll Worker #11/INFO]: [server connection] <username> -> lobby has connected
[06:36:13] [Netty epoll Worker #11/ERROR]: [connected player] <username> (/<ip address>): disconnected while connecting to lobby: multiplayer.disconnect.outdated_server
[06:36:13] [Netty epoll Worker #11/INFO]: [server connection] <username> -> lobby has disconnected
[06:36:13] [Netty epoll Worker #11/INFO]: [server connection] <username> -> lobby has connected
[06:36:13] [Netty epoll Worker #11/ERROR]: [connected player] <username> (/<ip address>): disconnected while connecting to lobby: multiplayer.disconnect.outdated_server
[06:36:13] [Netty epoll Worker #11/INFO]: [server connection] <username> -> lobby has disconnected
[06:36:13] [Netty epoll Worker #11/INFO]: [server connection] <username> -> lobby has connected
[06:36:13] [Netty epoll Worker #11/ERROR]: [connected player] <username> (/<ip address>): disconnected while connecting to lobby: multiplayer.disconnect.outdated_server
[06:36:13] [Netty epoll Worker #11/INFO]: [server connection] <username> -> lobby has disconnected
[06:36:13] [Netty epoll Worker #11/INFO]: [server connection] <username> -> lobby has connected
[06:36:13] [Netty epoll Worker #11/ERROR]: [connected player] <username> (/<ip address>): disconnected while connecting to lobby: multiplayer.disconnect.outdated_server
[06:36:13] [Netty epoll Worker #11/INFO]: [server connection] <username> -> lobby has disconnected
[06:36:13] [Netty epoll Worker #11/INFO]: [server connection] <username> -> lobby has connected
[06:36:13] [Netty epoll Worker #11/ERROR]: [connected player] <username> (/<ip address>): disconnected while connecting to lobby: multiplayer.disconnect.outdated_server
[06:36:13] [Netty epoll Worker #11/INFO]: [server connection] <username> -> lobby has disconnected
[06:36:13] [Netty epoll Worker #11/INFO]: [server connection] <username> -> lobby has connected
[06:36:13] [Netty epoll Worker #11/ERROR]: [connected player] <username> (/<ip address>): disconnected while connecting to lobby: multiplayer.disconnect.outdated_server
[06:36:13] [Netty epoll Worker #11/INFO]: [server connection] <username> -> lobby has disconnected
[06:36:13] [Netty epoll Worker #11/INFO]: [server connection] <username> -> lobby has connected
[06:36:13] [Netty epoll Worker #11/ERROR]: [connected player] <username> (/<ip address>): disconnected while connecting to lobby: multiplayer.disconnect.outdated_server
[06:36:13] [Netty epoll Worker #11/INFO]: [server connection] <username> -> lobby has disconnected`

**Comment by astei** [comment] 2019-02-16 07:08
Please try with the latest Velocity build. I believe i already fixed this in 02a72503.

**Comment by astei** [comment] 2019-02-21 14:34
What plugins are you running? Try as I might, but I am unable to reproduce this issue.

**Comment by ukdyl94** [comment] 2019-02-21 23:53
We have joinkick and breadboard.

**Comment by astei** [comment] 2019-02-22 04:13
I've noticed that joinkick has been in peoples' plugin list that have been having this issue.

**Comment by astei** [comment] 2019-02-23 03:26
Closing this issue. This is a bug in the JoinKick plugin, not Velocity. If it's an actual Velocity issue, then we can look at it again.

**Closed by astei** 2019-02-23 03:26 UTC
Labels: bug

**Comment by NEXUS2345** [comment] 2019-02-23 22:21
I have removed JoinKick from the server and issue is continuing to occur.
