### ISSUE TITLE
Expose changing of the query map in the config

### ISSUE THREAD

**Issue by DoNotSpamPls** [VelocityPowered/Velocity#92] opened 2018-09-16 17:42 UTC
This is not very high priority, but I'd like to be able to change the hardcoded "Velocity" map in the query response to something else. I think this was planned, looking at the original PR discussion, but was never executed.

Also, even more low priroity - it'd be nice if there is an opt-in option to expose the plugins of the proxy, since there are some voting sites (which are the primary reason query is enabled in the first place) reward with higher rankings if you show your plugins 

**cough** Minecraft-MP **cough cough**

**Comment by astei** [comment] 2018-09-16 17:43
I want to say that this is a duplicate of #47 (which basically gets to your point), but it's something we could add in, yes.

**Closed** 2018-09-24 12:14 UTC
Labels: enhancement
