### ISSUE TITLE
[1.1.0] Velocity doesn't fully send brigadier nodes, only ones who have .executes called

### ISSUE THREAD

**Issue by MrIvanPlays** [VelocityPowered/Velocity#337] opened 2020-07-29 09:27 UTC
```java
    LiteralCommandNode<CommandSource> builder =
        LiteralArgumentBuilder.<CommandSource>literal("mytestcommand")
            .requires((sender) -> true)
            .then(
                RequiredArgumentBuilder.<CommandSource, String>argument(
                        "arg1", StringArgumentType.string())
                    .requires((sender) -> true)
                    .suggests(
                        (context, suggestionsBuilder) -> {
                          suggestionsBuilder.suggest("hello");
                          suggestionsBuilder.suggest("world");
                          return suggestionsBuilder.buildFuture();
                        })
                    .executes(
                        (sender) -> {
                          CommandSource source = sender.getSource();
                          source.sendMessage(
                              TextComponent.of("Hello, world!").color(NamedTextColor.BLUE));
                          return 1;
                        }))
            .build();

    proxy.getCommandManager().register(new BrigadierCommand(builder));
```

**Expected behavior**
Shown by minecraft's /time command, but basically this is what we should get when we run /mytestcommand (code up):
![expected](https://img.mrivanplays.com/javaw_Q5QGv2OVOZ.png)

**Observed behavior**
Shows Bukkit's unknown command message

**Environment**
Paper 1.15.2 as backend server (yes too lazy 2 update)
![velocity version](https://img.mrivanplays.com/javaw_9W9EmyfhgL.png)

**Comment by hugmanrique** [comment] 2020-07-29 09:39
This mimicks Velocity's 1.0.x behavior of redirecting unknown commands to the backend server. This was discussed on the PR.

**Comment by astei** [comment] 2020-07-29 09:41
Closing as intended behavior. We should consider an option to allow the commands to be blocked at this high level if desired, though.

**Closed by astei** 2020-07-29 09:41 UTC
Labels: bug

**Comment by MrIvanPlays** [comment] 2020-07-29 09:43
> This mimicks Velocity's 1.0.x behavior of redirecting unknown commands to the backend server. This was discussed on the PR.
> 
> Did you get a syntax error message however? This check might be broken:
> 
> https://github.com/VelocityPowered/Velocity/blob/89f98ce57de0d87da00ef9793ee16f4ce03cb479/proxy/src/main/java/com/velocitypowered/proxy/command/VelocityCommandManager.java#L163

No I didn't.

**Comment by astei** [comment] 2020-07-29 09:54
> In my opinion you should make it so brigadier commands are fully handled by brigadier, and if a plugin registers a legacy type command to do whatever you do.

That will require some more radical changes to the command API (since we still want to be able to forward to the backend server too) but it is doable.

**Comment by MrIvanPlays** [comment] 2020-07-29 09:58
Well then keep it like that. Also a question: does velocity transform brigadier nodes to legacy type commands if the command is executed at version < 1.13 ?

**Comment by astei** [comment] 2020-07-29 09:59
No, it is handled normally. Brigadier commands are backwards-compatible with 1.12.2 and below, clients will simply not get hinting suggestions.

**Comment by MrIvanPlays** [comment] 2020-07-29 10:02
wdym by hinting? required argument without .suggests ?

**Comment by astei** [comment] 2020-07-29 10:21
4c5636e6 should fix that.

Hinting is quite literally the client having the command tree and giving you suggestions.

**Comment by MrIvanPlays** [comment] 2020-07-29 10:35
> [4c5636e](https://github.com/VelocityPowered/Velocity/commit/4c5636e6f74b23fc773eceb6588ae8b51ac2d4c5) should fix that.
> 
> Hinting is quite literally the client having the command tree and giving you suggestions.

Confirm this resolves it.
