### ISSUE TITLE
Multiple forwarding secrets

### ISSUE THREAD

**Issue by scriptcoded** [VelocityPowered/Velocity#331] opened 2020-07-17 08:02 UTC
Hey,

Great job with Velocity! I'm currently using it to tie together local servers through tunneled connections. I'm basically allowing people to run servers on their local computers and expose their servers without having to port forward. Velocity fits right in here, as I can use it to attach domain names to specific ports and servers. One thing that has got me a little worried though is the forwarding secret. To enable modern forwarding this secret must be present in the config of each server instance, but since these servers are distributed the key is replicated across multiple hosts. As far as I can tell from the documentation there is no way to provide multiple forwarding secrets? A feature like that would not only solve my issue, but also allow for rotating keys.

Keep up the great work!
Malcolm

**Comment by scriptcoded** [comment] 2020-09-18 09:56
I recently got back to this project of mine, only to realize that the keys might be an issue. While searching on GH I found that I had already submitted an issue :sweat_smile: 

@astei would you say that this feature is of interest for Velocity? If so I might go ahead and create a PR when I get to the point that this feature is make or break for my own project.

**Comment by astei** [comment] 2020-10-22 06:35
Targeting this for Velocity 2.0.0.

**Comment by astei** [comment] 2021-05-12 13:11
I'm closing this issue as I just realized it's a duplicate of #304

**Closed by astei** 2021-05-12 13:11 UTC
Labels: enhancement
